const assert=require('node:assert/strict');
const {Conversation,parse,due,defaults}=require('../web/static/companion/assistant-core.js');
const c=new Conversation();
assert.equal(c.feed('拿烧杯',0).action,'ignore');
assert.equal(c.feed('小乐小乐',10).action,'wake');
assert.equal(c.feed('拿烧杯',20).preset,'small_cup_full_cycle_01');
assert.equal(c.feed('拿烧杯',21).action,'ignore');
assert.equal(c.feed('小乐小乐',4000).action,'wake');
assert.equal(c.tick(19001),true);
assert.equal(c.feed('拿烧杯',19002).action,'ignore');
assert.equal(c.feed('停止',19003).action,'stop');
assert.equal(c.feed('小乐小乐，把药送给我',20000).preset,'bring_medicine_demo_01');
assert.equal(parse('不要拿药').action,'clarify');
assert.equal(parse('可以拿烧杯吗').action,'clarify');
assert.equal(parse('烧杯').action,'clarify');
assert.equal(parse('拿小烧杯').preset,'small_cup_full_cycle_01');
assert.equal(parse('帮我拿杯子').preset,'small_cup_full_cycle_01');
assert.equal(parse('取消').action,'cancel');
assert.equal(parse('今天有什么安排').action,'schedule');
const routines=defaults.map(r=>({...r,enabled:true}));
const at=new Date('2026-09-11T05:00:00Z');
assert.equal(due(routines,at,'Europe/Helsinki',{})[0].routine.id,'morning');
assert.equal(due(routines,at,'Europe/Helsinki',{morning:'2026-09-11'}).length,0);
assert.equal(due(defaults,at,'Europe/Helsinki',{}).length,0);
console.log('PASS: wake gate, timeout, deduplication, stop, negation, daily reminders');
